import { NextResponse } from "next/server";
import { demoMerchantGrowth, type MerchantData, type MerchantOpportunity } from "@/lib/merchant";
import { generateOllamaJson, OllamaProviderError } from "@/lib/ollama";
export const runtime = "nodejs";
const types = new Set(["upsell", "cross_sell", "product_improvement", "campaign"]);
const priorities = new Set(["High", "Medium", "Low"]);
function validData(value: unknown): value is MerchantData { return !!value && typeof value === "object" && Array.isArray((value as MerchantData).products) && Array.isArray((value as MerchantData).combinations) && (value as MerchantData).products.length > 0; }
function valid(value: unknown, merchant: MerchantData): value is { summary: string; opportunities: MerchantOpportunity[] } { if (!value || typeof value !== "object") return false; const data = value as Record<string, unknown>; const productNames = new Set(merchant.products.map((product) => product.product)); const evidenceNumbers = [ ...merchant.products.flatMap((product) => [product.views, product.detailViews, product.addToCart, product.purchases, product.revenue]), ...merchant.combinations.map((combination) => combination.customersPurchasingBoth) ].map(String); return typeof data.summary === "string" && Array.isArray(data.opportunities) && data.opportunities.every((item) => { const opportunity = item as MerchantOpportunity; return item && typeof item === "object" && types.has(opportunity.type) && priorities.has(opportunity.priority) && productNames.has(opportunity.product) && (!opportunity.relatedProduct || productNames.has(opportunity.relatedProduct)) && typeof opportunity.evidence === "string" && evidenceNumbers.some((number) => opportunity.evidence.includes(number)) && typeof opportunity.recommendation === "string" && typeof opportunity.expectedImpact === "string" && Array.isArray(opportunity.metrics) && opportunity.metrics.length > 0; }); }
export async function POST(request: Request) { try { const { merchant } = await request.json() as { merchant?: MerchantData }; if (!validData(merchant)) return NextResponse.json({ error: "Invalid merchant data." }, { status: 400 }); if (process.env.MOCK_AI_MODE === "true") return NextResponse.json({ summary: "DEMO MODE — Opportunities are derived from the supplied demo merchant products and purchase combinations.", opportunities: demoMerchantGrowth(merchant), demo: true }); const output = await generateOllamaJson(`Use only this merchant data: ${JSON.stringify(merchant)}. Do not invent values or relationships. Return JSON only: {summary,opportunities:[{id,type:"upsell|cross_sell|product_improvement|campaign",title,priority:"High|Medium|Low",product,relatedProduct,evidence,recommendation,expectedImpact,metrics:string[]}]}. Every evidence and metric must include exact supplied product names and numeric values.`, 1800); if (!valid(output, merchant)) return NextResponse.json({ error: "Growth analysis is temporarily unavailable. Please try again later." }, { status: 502 }); return NextResponse.json({ ...output, demo: false }); } catch (error) { const status = error instanceof OllamaProviderError ? error.status : undefined; return NextResponse.json({ error: "Growth analysis is temporarily unavailable. Please try again later." }, { status: status === 429 ? 429 : 502 }); } }
