import { NextResponse } from "next/server";
import { generateAiJson, AiProviderError, isMockAiMode } from "@/lib/ai-provider";
import { isGrowthAnalysis, normalizeGrowthAnalysis } from "@/lib/growth-analysis";
import type { Company } from "@/types/company";
import { companyFunding, companyIndustry, companyInvestors, companyText } from "@/lib/companies";
export const runtime = "nodejs";
function context(company: Company) { return { name: companyText(company.name), city: companyText(company.city), state: companyText(company.state), category: companyText(company.category), industry: companyIndustry(company), description: companyText(company.description), website: companyText(company.website), funding: companyFunding(company), investors: companyInvestors(company) }; }
function demo(company: Company) { const industry = companyIndustry(company) ?? companyText(company.category) ?? "technology"; return { opportunity: `Build a focused ${industry} acquisition motion in ${company.city}.`, why: "Use the available company profile to run a measured go-to-market experiment.", targetSegment: `High-intent ${industry} customers in ${company.city}.`, strategy: "Define one priority segment, refine its value proposition, and measure one acquisition channel.", expectedImpact: "A clearer acquisition funnel and a repeatable growth channel after validation.", difficulty: "Medium" as const, priority: "High" as const, kpis: ["Qualified acquisition", "Activation rate", "Conversion rate"] }; }
export async function POST(request: Request) { try { const { company } = await request.json() as { company?: Company }; if (!company || !companyText(company.name) || !companyText(company.city)) return NextResponse.json({ error: "Invalid company data." }, { status: 400 }); if (isMockAiMode()) return NextResponse.json({ analysis: demo(company), demo: true }); const value = normalizeGrowthAnalysis(await generateAiJson(`Use only these company facts: ${JSON.stringify(context(company))}. Do not invent facts. Return JSON only. Required shape: {"opportunity":"string","why":"string","targetSegment":"string","strategy":"string","expectedImpact":"string","difficulty":"Medium","priority":"High","kpis":["string"]}. expectedImpact must be one string, not an array. difficulty and priority must each be exactly one of "Low", "Medium", or "High". Never use pipe characters or list all possible levels.`, 2048)); if (!isGrowthAnalysis(value)) return NextResponse.json({ error: "Unable to generate growth analysis right now." }, { status: 502 }); return NextResponse.json({ analysis: value, demo: false }); } catch (error) { const status = error instanceof AiProviderError ? error.status : undefined; return NextResponse.json({ error: "Unable to generate growth analysis right now." }, { status: status === 429 ? 429 : 502 }); } }
