import { NextResponse } from "next/server";
import { generateOllamaJson, OllamaProviderError } from "@/lib/ollama";
import type { Company } from "@/types/company";
import { isGrowthAnalysis } from "@/lib/growth-analysis";
import { companyIndustry, companyText } from "@/lib/companies";
export const runtime = "nodejs";
const levels = new Set(["Low", "Medium", "High"]);
function valid(value: unknown) { if (!value || typeof value !== "object") return false; const v = value as Record<string, unknown>; return levels.has(v.overallRisk as string) && typeof v.overallScore === "number" && typeof v.summary === "string" && typeof v.keyRisk === "string" && typeof v.recommendation === "string" && Array.isArray(v.risks) && v.risks.length === 6 && v.risks.every(r => r && typeof r === "object" && typeof (r as Record<string, unknown>).category === "string" && levels.has((r as Record<string, unknown>).level as string) && typeof (r as Record<string, unknown>).score === "number" && typeof (r as Record<string, unknown>).reason === "string" && typeof (r as Record<string, unknown>).mitigation === "string"); }
function demo(company: Company) { const seed = [...`${company.id}-${company.city}-${company.category}`].reduce((total, character) => (total * 31 + character.charCodeAt(0)) % 53, 0); const risks = ["Competition", "Market", "Funding", "Customer Acquisition", "Execution", "Geographic"].map((category, index) => { const score = 28 + ((seed + index * 11) % 48); return { category: `${category} Risk`, level: score > 66 ? "High" as const : score > 40 ? "Medium" as const : "Low" as const, score, reason: company.description ? `TechAtlas estimated ${category.toLowerCase()} risk from the available ${company.city} company profile.` : "Insufficient data available.", mitigation: "Validate assumptions with focused research and measured pilots." }; }); const key = risks.slice().sort((a, b) => b.score - a.score)[0]; const overallScore = Math.round(risks.reduce((total, risk) => total + risk.score, 0) / risks.length); return { overallRisk: overallScore > 66 ? "High" : overallScore > 40 ? "Medium" : "Low", overallScore, summary: `TechAtlas estimated risks based on available company and market information for ${company.name}.`, risks, keyRisk: key.category, recommendation: `Prioritize ${key.category.toLowerCase()} before scaling.` }; }
export async function POST(request: Request) { try { const { company, growthAnalysis } = await request.json() as { company?: Company; growthAnalysis?: unknown }; if (!company || !companyText(company.name)) return NextResponse.json({ error: "Invalid company data." }, { status: 400 }); if (growthAnalysis && !isGrowthAnalysis(growthAnalysis)) return NextResponse.json({ error: "Invalid growth analysis provided." }, { status: 400 }); if (process.env.MOCK_AI_MODE === "true") return NextResponse.json({ analysis: demo(company), demo: true }); const value = await generateOllamaJson(`Use only supplied facts. Return JSON only: {overallRisk:"Low|Medium|High",overallScore:number,summary,keyRisk,recommendation,risks:[6 objects with category,level:"Low|Medium|High",score:number,reason,mitigation]}. Company: ${JSON.stringify({ name: company.name, city: company.city, industry: companyIndustry(company), category: company.category, description: company.description })}. Growth analysis: ${JSON.stringify(growthAnalysis ?? null)}.`, 1400); if (!valid(value)) return NextResponse.json({ error: "Unable to generate risk analysis right now." }, { status: 502 }); return NextResponse.json({ analysis: value, demo: false }); } catch (error) { const status = error instanceof OllamaProviderError ? error.status : undefined; return NextResponse.json({ error: "Unable to generate risk analysis right now." }, { status: status === 429 ? 429 : 502 }); } }
