"use client";

import { useMemo, useState } from "react";
import { merchantData, merchantTotals, type MerchantOpportunity } from "@/lib/merchant";

type Status = "pending" | "approved" | "rejected" | "executed";
export default function MerchantGrowthDashboard() {
  const [opportunities, setOpportunities] = useState<MerchantOpportunity[]>([]);
  const [selected, setSelected] = useState<MerchantOpportunity | null>(null);
  const [statuses, setStatuses] = useState<Record<string, Status>>({});
  const [executingId, setExecutingId] = useState<string | null>(null);
  const [loading, setLoading] = useState(false); const [error, setError] = useState(false); const [demo, setDemo] = useState(process.env.NEXT_PUBLIC_MOCK_AI_MODE === "true");
  const totals = merchantTotals(merchantData);
  const summary = useMemo(() => ({ total: opportunities.length, high: opportunities.filter((item) => item.priority === "High").length, medium: opportunities.filter((item) => item.priority === "Medium").length, low: opportunities.filter((item) => item.priority === "Low").length }), [opportunities]);
  const analyze = async () => { setLoading(true); setError(false); try { const response = await fetch("/api/merchant/growth", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ merchant: merchantData }) }); const data = await response.json(); if (!response.ok || !Array.isArray(data.opportunities)) throw new Error("growth"); setOpportunities(data.opportunities); setDemo(Boolean(data.demo)); } catch { setError(true); } finally { setLoading(false); } };
  const setStatus = (id: string, status: Status) => { setStatuses((previous) => ({ ...previous, [id]: status })); if (selected?.id === id && status !== "pending") setSelected(null); };
  const execute = (id: string) => { setExecutingId(id); window.setTimeout(() => { setStatus(id, "executed"); setExecutingId(null); }, 650); };
  const approved = opportunities.filter((item) => statuses[item.id] === "approved" || statuses[item.id] === "executed");
  const topRevenueProduct = merchantData.products[0];
  const topTrafficProduct = [...merchantData.products].sort((left, right) => right.views - left.views)[0];
  return <div className="mt-7 space-y-6">
    <section className="grid grid-cols-2 gap-3 md:grid-cols-5"><Kpi label="Recorded revenue" value={`$${(totals.revenue / 1000000).toFixed(1)}M`} /><Kpi label="Purchases" value={totals.orders.toLocaleString("en-US")} /><Kpi label="Average order value" value={`$${totals.averageOrderValue.toLocaleString("en-US")}`} /><Kpi label="Conversion rate" value={`${totals.conversionRate}%`} /><Kpi label="Product views" value={`${(totals.views / 1000000).toFixed(1)}M`} /></section>
    <section className="theme-surface rounded-lg border p-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[.16em] text-sky-300">Merchant intelligence</p><h2 className="mt-2 text-xl font-semibold">Discover evidence-based growth opportunities</h2><p className="mt-1 max-w-3xl text-sm text-slate-400">Historical source: {merchantData.source}. Aggregated from {merchantData.events.toLocaleString("en-US")} recorded events; prices are reported in USD.</p></div><button onClick={() => void analyze()} disabled={loading} className="rounded border border-sky-400/40 bg-sky-500/10 px-4 py-2.5 text-sm font-medium text-sky-100 hover:bg-sky-500/20 disabled:opacity-50">{loading ? "ANALYZING MERCHANT DATA..." : "Analyze Growth Opportunities"}</button></div>{error ? <p className="mt-4 text-sm text-rose-300">Growth analysis is temporarily unavailable. Please try again later.</p> : null}</section>
    <section className="grid gap-4 lg:grid-cols-3"><Info title="Archive Insights" items={[`${topTrafficProduct?.product ?? "Top product"} has the highest recorded traffic in the imported product set.`, `${topRevenueProduct?.product ?? "Top product"} leads this set by recorded purchase revenue.`, "Product-combination metrics are not shown because this compact import does not infer session-level relationships."]} /><Info title="Data Coverage" items={["Top 30 products are ranked by recorded purchase revenue.", "Views, cart events, purchases, and recorded purchase revenue are derived directly from the archive.", "The source is historical data, not a live merchant store feed."]} /><Info title="Action Safety" items={["No live store, payment, campaign, or customer data is connected.", "Merchant approval is required before every simulated execution."]} /></section>
    <section className="theme-surface overflow-x-auto rounded-lg border p-5"><h2 className="text-sm font-semibold uppercase tracking-[.14em]">Imported Product Performance</h2><table className="mt-4 min-w-[840px] w-full text-left text-sm"><thead className="text-xs uppercase tracking-wide text-slate-400"><tr><th>Product</th><th>Brand</th><th>Views</th><th>Add to cart</th><th>Purchases</th><th>Conversion</th><th>Recorded revenue</th></tr></thead><tbody>{merchantData.products.map((product) => <tr key={product.productId} className="border-t border-white/10"><td className="py-3 font-medium">{product.product}</td><td>{product.brand}</td><td>{product.views.toLocaleString("en-US")}</td><td>{product.addToCart.toLocaleString("en-US")}</td><td>{product.purchases.toLocaleString("en-US")}</td><td>{((product.purchases / product.views) * 100).toFixed(2)}%</td><td>${product.revenue.toLocaleString("en-US", { maximumFractionDigits: 0 })}</td></tr>)}</tbody></table></section>
    {opportunities.length ? <section><div className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs uppercase tracking-[.16em] text-sky-300">Growth Opportunity Summary {demo ? "· DEMO MODE" : ""}</p><h2 className="mt-1 text-xl font-semibold">{summary.total} Growth Opportunities</h2></div><p className="text-sm text-slate-400">{summary.high} High · {summary.medium} Medium · {summary.low} Low priority</p></div><div className="grid gap-4 md:grid-cols-2">{opportunities.map((opportunity) => <OpportunityCard key={opportunity.id} opportunity={opportunity} status={statuses[opportunity.id] ?? "pending"} onReview={() => setSelected(opportunity)} />)}</div></section> : null}
    {approved.length ? <section className="theme-surface rounded-lg border p-5"><p className="text-xs uppercase tracking-[.16em] text-sky-300">Action Center · DEMO MODE</p><h2 className="mt-2 text-lg font-semibold">Approved Growth Actions</h2><div className="mt-4 space-y-3">{approved.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded border border-white/10 p-3"><div><p className="font-medium">{item.title}</p><p className="text-xs text-slate-400">{item.type.replace("_", " ")} · {statuses[item.id] === "executed" ? "Demo Executed" : "Approved"}</p></div>{statuses[item.id] === "executed" ? <Performance opportunity={item} /> : <button onClick={() => execute(item.id)} disabled={executingId === item.id} className="rounded border border-emerald-400/40 bg-emerald-500/10 px-3 py-2 text-sm text-emerald-200 disabled:opacity-50">{executingId === item.id ? "EXECUTING DEMO ACTION..." : "Execute Action"}</button>}</div>)}</div></section> : null}
    {selected ? <Review opportunity={selected} status={statuses[selected.id] ?? "pending"} onClose={() => setSelected(null)} onApprove={() => setStatus(selected.id, "approved")} onReject={() => setStatus(selected.id, "rejected")} /> : null}
  </div>;
}
function Kpi({ label, value }: { label: string; value: string }) { return <div className="theme-surface rounded-lg border p-4"><p className="text-xs uppercase tracking-[.12em] text-slate-400">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p><p className="mt-1 text-[10px] text-slate-500">HISTORICAL EVENT DATA</p></div>; }
function Info({ title, items }: { title: string; items: string[] }) { return <section className="theme-surface rounded-lg border p-4"><h2 className="text-sm font-semibold uppercase tracking-[.14em]">{title}</h2><ul className="mt-3 space-y-2 text-sm leading-5 text-slate-300">{items.map((item) => <li key={item}>{item}</li>)}</ul></section>; }
function OpportunityCard({ opportunity, status, onReview }: { opportunity: MerchantOpportunity; status: Status; onReview: () => void }) { return <article className="theme-surface rounded-lg border border-sky-400/15 p-5"><div className="flex items-start justify-between gap-3"><p className="text-xs uppercase tracking-[.14em] text-sky-300">{opportunity.type.replace("_", " ")}</p><span className="rounded border border-white/10 px-2 py-1 text-xs text-slate-300">{opportunity.priority} priority</span></div><h3 className="mt-3 text-lg font-semibold">{opportunity.title}</h3><p className="mt-2 text-sm text-slate-300">{opportunity.product}{opportunity.relatedProduct ? ` → ${opportunity.relatedProduct}` : ""}</p><p className="mt-4 text-xs uppercase tracking-[.12em] text-slate-400">Why this was identified</p><p className="mt-1 text-sm text-slate-200">{opportunity.evidence}</p><p className="mt-4 text-xs uppercase tracking-[.12em] text-slate-400">Recommendation</p><p className="mt-1 text-sm text-slate-200">{opportunity.recommendation}</p><div className="mt-4 flex items-center justify-between"><span className="text-xs text-slate-400">Status: {status.replace("_", " ").toUpperCase()}</span><button onClick={onReview} className="rounded border border-sky-400/40 px-3 py-2 text-sm text-sky-100 hover:bg-sky-500/10">Review Opportunity</button></div></article>; }
function Review({ opportunity, status, onClose, onApprove, onReject }: { opportunity: MerchantOpportunity; status: Status; onClose: () => void; onApprove: () => void; onReject: () => void }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4 backdrop-blur-sm"><section className="theme-surface max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-lg border p-6"><button onClick={onClose} className="float-right text-sm text-slate-400">Close</button><p className="text-xs uppercase tracking-[.16em] text-sky-300">Growth Opportunity · DEMO MODE</p><h2 className="mt-2 text-2xl font-semibold">{opportunity.title}</h2><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2"><Detail label="Type" value={opportunity.type.replace("_", " ")} /><Detail label="Product" value={opportunity.product} /><Detail label="Recommended product" value={opportunity.relatedProduct || "Insufficient data available."} /><Detail label="Status" value={status === "pending" ? "PENDING REVIEW" : status.toUpperCase()} /></dl><h3 className="mt-6 text-xs uppercase tracking-[.14em] text-slate-400">Why</h3><p className="mt-2 text-sm text-slate-200">{opportunity.evidence}</p><h3 className="mt-5 text-xs uppercase tracking-[.14em] text-slate-400">Data Used</h3><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-300">{opportunity.metrics.map((metric) => <li key={metric}>{metric}</li>)}</ul><h3 className="mt-5 text-xs uppercase tracking-[.14em] text-slate-400">Expected Impact</h3><p className="mt-2 text-sm text-slate-200">{opportunity.expectedImpact}</p>{status === "pending" ? <div className="mt-6 flex gap-3"><button onClick={onApprove} className="rounded bg-sky-400 px-4 py-2 text-sm font-medium text-slate-950">Approve Action</button><button onClick={onReject} className="rounded border border-white/15 px-4 py-2 text-sm text-slate-200">Reject</button></div> : <p className="mt-6 text-sm text-emerald-300">{status === "rejected" ? "ACTION REJECTED — This recommendation will not be executed." : "Merchant approved this growth action."}</p>}</section></div>; }
function Detail({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-slate-400">{label}</dt><dd className="mt-1 text-sm text-slate-100">{value}</dd></div>; }
function Performance({ opportunity }: { opportunity: MerchantOpportunity }) { return <div className="rounded border border-emerald-400/25 bg-emerald-500/5 p-3 text-xs text-emerald-100"><p className="font-medium">DEMO EXECUTION · ACTION EXECUTED</p><p className="mt-1">Demo performance metrics: 1,240 views · 96 clicks · 24 conversions · 2.5% conversion rate · ₹24,000 revenue.</p><p className="mt-1 text-emerald-200">No real merchant store was changed.</p></div>; }
