"use client";
import { useMemo, useState } from "react";
import type { Company } from "@/types/company";
import { companyFunding, companyIndustry } from "@/lib/companies";
import { fundingAmount } from "@/lib/investor";

export function CompanyDirectory({ city, companies, selectedId, onSelect }: { city: string; companies: Company[]; selectedId: string | null; onSelect: (company: Company) => void }) {
  const [query, setQuery] = useState(""); const [sort, setSort] = useState("signals");
  const rows = useMemo(() => companies.filter((company) => `${company.name} ${companyIndustry(company) ?? company.category ?? ""}`.toLowerCase().includes(query.toLowerCase())).sort((a,b) => sort === "name" ? a.name.localeCompare(b.name) : sort === "funding" ? (fundingAmount(b) ?? -1) - (fundingAmount(a) ?? -1) : ((fundingAmount(b) ?? -1) - (fundingAmount(a) ?? -1)) || (Number(Boolean(b.description))+Number(Boolean(b.website))) - (Number(Boolean(a.description))+Number(Boolean(a.website))) || a.name.localeCompare(b.name)).slice(0,30), [companies,query,sort]);
  return <aside className="theme-surface pointer-events-auto absolute bottom-16 left-5 z-10 w-[min(15rem,calc(100%-2.5rem))] rounded-lg border border-white/10 bg-slate-950/85 p-2.5 shadow-[0_12px_36px_rgba(0,0,0,.25)] backdrop-blur-md sm:bottom-auto sm:left-auto sm:right-6 sm:top-44 sm:w-64"><p className="px-1 text-[10px] font-medium uppercase tracking-[.14em] text-sky-300">Top Companies in {city}</p><p className="mt-1 px-1 text-[10px] text-slate-500">{rows.length} companies · available dataset signals</p><div className="mt-2 flex gap-1"><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search companies..." className="min-w-0 flex-1 rounded bg-white/5 px-2 py-1.5 text-xs text-slate-100 placeholder:text-slate-500 focus:outline-none"/><select value={sort} onChange={(e)=>setSort(e.target.value)} className="rounded bg-white/5 px-1 text-[10px] text-slate-200"><option value="signals">Signals</option><option value="name">A-Z</option><option value="funding">Funding</option></select></div><ul className="mt-2 max-h-60 space-y-1 overflow-y-auto pr-0.5">{rows.map((company)=>{const sector=companyIndustry(company) ?? company.category;const funding=companyFunding(company);return <li key={company.id}><button onClick={()=>onSelect(company)} className={`flex w-full items-center gap-2 rounded-md p-2 text-left transition ${selectedId===company.id?"bg-sky-400/15 ring-1 ring-sky-300/40":"hover:bg-white/5"}`}><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-sky-400/15 text-xs font-semibold text-sky-200">{company.name.slice(0,2).toUpperCase()}</span><span className="min-w-0"><span className="block truncate text-xs font-medium text-white">{company.name}</span>{sector || funding ? <span className="block truncate text-[10px] text-slate-400">{[sector,funding].filter(Boolean).join(" · ")}</span>:null}</span></button></li>})}</ul><p className="mt-2 px-1 text-[9px] text-slate-500">Not investment advice.</p></aside>;
}
